### ISSUE TITLE
Error thrown: table photos has no column named hasSticker

### ISSUE THREAD

**Issue by harperreed** [dogsheep/swarm-to-sqlite#8]
While running `swarm-to-sqlite` it throws an error:

    harper@:~/dogsheep/swarm$ swarm-to-sqlite checkins.db --save=checkins.json
    Please provide your Foursquare OAuth token:
    Importing 8127 checkins  [#################-------------------]   49%  00:01:52
    Traceback (most recent call last):
    File "/home/harper/.local/bin/swarm-to-sqlite", line 11, in <module>
        sys.exit(cli())
    File "/home/harper/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
        return self.main(*args, **kwargs)
    File "/home/harper/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
        rv = self.invoke(ctx)
    File "/home/harper/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
        return ctx.invoke(self.callback, **ctx.params)
    File "/home/harper/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
        return callback(*args, **kwargs)
    File "/home/harper/.local/lib/python3.6/site-packages/swarm_to_sqlite/cli.py", line 73, in cli
        save_checkin(checkin, db)
    File "/home/harper/.local/lib/python3.6/site-packages/swarm_to_sqlite/utils.py", line 94, in save_checkin
        photos_table.insert(photo, replace=True)
    File "/home/harper/.local/lib/python3.6/site-packages/sqlite_utils/db.py", line 963, in insert
        alter = self.value_or_default("alter", alter)
    File "/home/harper/.local/lib/python3.6/site-packages/sqlite_utils/db.py", line 1142, in insert_all
        def upsert_all(
    sqlite3.OperationalError: table photos has no column named hasSticker

Where should i dig in?

**Comment by simonw** [comment]
Looks like there's a column that's not consistently there, so the table got created without it.

Easiest fix is to add `alter=True` to this line:

https://github.com/dogsheep/swarm-to-sqlite/blob/f4a82633da927cde672c9d9af92930bfca2e3ddf/swarm_to_sqlite/utils.py#L94

That will cause `sqlite-utils` to notice if there's a missing column and add it.

**Comment by simonw** [comment]
Shipped a fix for this in [swarm-to-sqlite 0.3.2](https://github.com/dogsheep/swarm-to-sqlite/releases/tag/0.3.2).
